### ISSUE TITLE
Seems like lot of things need to be implemented!

### ISSUE THREAD

**Issue by ks1990cn** [sachintha00/School-Management-System#1]
Currently this application opens at login page, which should have create new user option too.
No security while storing and getting from database
No try catch
No async
Not implement admin roles etc etc.

**Comment by sachintha00** [comment]
> Currently this application opens at login page, which should have create new user option too. No security while storing and getting from database No try catch No async Not implement admin roles etc etc.

This application is not yet complete bro😊 Thanks for pointing out the shortcomings😙

**Comment by ks1990cn** [comment]
No maintenance further on this project ... Closing Issue now.
